### ISSUE TITLE
i got 2 error 

### ISSUE THREAD

**Issue by pisedx** [Nikolas-Charalambidis/google-scripts#1]
🚫 SCRIPT ERROR [TypeError: Cannot read properties of undefined (reading 'postData')]
ReferenceError: data is not defined
doPost	@ รหัส.gs:98

-------------------------
Error	
TypeError: Cannot read properties of undefined (reading 'replyToken')
reply	@ รหัส.gs:117

**Comment by nikolas-charalambidis** [comment]
@pisedx The script is not meant to be runnable directly from the Google Sheet app as long as no Line event `e` is sent. The Line has to be integrated with Google Sheets. All the further errors are derived from this fact.

I am not a Line API expert and I don't even use such an app. I only helped my friend by adjusting the script for their use case. 

Please, refer to the YouTube [channel](https://www.youtube.com/@iton5) of [iton5](https://gist.github.com/iton5) to gather more information about Line and how this thing works.
